<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'GodataRest\Module'                        => __DIR__ . '/Module.php',
    'GodataRest\Controller\Article\Article' => __DIR__ . '/src/GodataRest/Controller/Article/Article.php',
);
